version: '3.1'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastfeet
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    image: node:alpine
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./../backend/:/home/node/app
    command: >
      sh -c "npm install && 
             npx cross-env NODE_ENV=docker sequelize db:migrate && 
             npx cross-env NODE_ENV=docker sequelize db:seed:all && 
             npm run docker"
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  web:
    image: node:alpine
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./../frontend/:/home/node/app
    command: >
      sh -c "npm install && 
             npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - backend 
volumes:
  dbdata: